# -*- coding: utf-8 -*-
"""
This module allow a connection to a haystack server
See documentation for all details.

If you want to know more about project-haystack visit :
http://www.project-haystack.org

Project Haystack is an open source initiative to streamline working with data from the Internet of Things. We standardize semantic data models and web services with the goal of making it easier to unlock value from the vast quantity of data being generated by the smart devices that permeate our homes, buildings, factories, and cities. Applications include automation, control, energy, HVAC, lighting, and other environmental systems.

"""

__author__ = 'Christian Tremblay, Stuart Longland, @sudo-Whateverman, Igor'
__author_email__ = 'christian.tremblay@servisys.com'
__version__ = '0.92'
__license__ = 'Apache 2.0'
__copyright__ = "Christian Tremblay / SERVISYS inc. | Stuart Longland / VRT | 2016"
